### PR TITLE
Clarification of SC - Nodes commands

### PR DESCRIPTION
**Pull request by Isax03**
This PR updates the documentation to address a potential source of confusion in the Simulation Controller (SC) command protocol. Specifically, the SC commands and events have been restricted to drones, as they were mistakenly described as applicable to all nodes (including clients and servers). The changes reflect the following rationale:

1. **Unnecessary Overhead for Clients and Servers**:
   - Most commands (`PacketDropped`, `Crash`, `SetPacketDropRate`) are only relevant to drones and serve no purpose for clients or servers.
   - This avoids imposing unnecessary constraints or requiring additional attributes for clients and servers to communicate with the SC.

2. **Customizability**:
   - `AddSender(dst_id, crossbeam::Sender)` and `PacketSent(packet)` are the only potentially useful commands for clients and servers. Groups can now define their own commands for hosts (clients/servers) in separate, custom enums tailored to their needs.

>  Note: I also removed an unnecessary and nonsensical section, probably the result of an erroneous copy/paste, as I didn’t want to create two separate PRs for something trivial.

### CODE REVIEW

**Comment by RickyBenevelli** [comment]
good fix

**Comment by matteo-dinoia** [comment]
AddSender(dst_id, crossbeam::Sender) and PacketSent(packet)
But we also need RemoveSender

**Comment by Isax03** [comment]
> But we also need RemoveSender

Yeah, now I'll add, I don't know why there isn't that command

---
> So we would need 4 enums.

I don't understand... What do you mean? In the common crate we only need 2 enums: `DroneCommands` and `DroneEvent`. Other enums are at the discretion of the group.

---
> Also (maybe not yet, wait still) you need to change also the code.

Sure, I forgot to change it

**Comment by matteo-dinoia** [comment]
4 enums as in:
1. type to be sent SC to Drone (+viceversa)
2. type to be sent SC to Client/Server (+viceversa)

I'm not saying it is the best way to do it. But that is what you are proposining in a way.

**Comment by Isax03** [comment]
Yes, but implementing the second point in the common crate isn't necessary. The interaction between SC and Client or Server can vary depending on each group's specific implementation

**Comment by matteo-dinoia** [comment]
> Yes, but implementing the second point in the common crate isn't necessary. The interaction between SC and Client or Server can vary depending on each group's specific implementation

No? They should be standard and decided now. The SC does not communicate in any strange way to the client, like it shouldn't ask the client to send a message. We really should ask the professor how the client work.

**Comment by Isax03** [comment]
No. If a group decides to share specific information with the SC, such as retrieving periodic values from clients and displaying them on a UI, this could involve custom request/response channels with a custom enum. In such cases, the SC-client and SC-server interactions can be tailored to each group's needs

**Pull request merged**
