### PR TITLE
Adding derive Clone and Debug to all struct

### PR DESCRIPTION
**Pull request by matteo-dinoia**
This cannot be done by the single groups, so we should do it for everyone so if someone need it for some struct it can use it.

### CODE REVIEW

**Comment by DiCesareDaniele** [comment]
I would also add PartialEq, Eq to ServerType and NodeType

**Comment by matteo-dinoia** [comment]
> I would also add PartialEq, Eq to ServerType and NodeType

Fair, I'll add to any that make sense. For the rest being a stupidy small change do you thing, it is ok so we can merge it?

**Comment by matteo-dinoia** [comment]
Other place we could add to is the message/packet, to some of the component but it seem excessive because in most case there is a unique id just for that.

**Comment by DiCesareDaniele** [comment]
> Other place we could add to is the message/packet, to some of the component but it seem excessive because in most case there is a unique id just for that.

Nah that is overkill I think it's fine RN

**Pull request merged**
