### PR TITLE
Add query and query result to packet types (+use NodeId)

### PR DESCRIPTION
**Pull request by matteo-dinoia**

### CODE REVIEW

**Comment by DiCesareDaniele** [comment]
Nice. I think we can approve this without a vote since it was already part of the code inside protocol

**Comment by DiCesareDaniele** [comment]
One thing I noticed is that this is not updating examples/drones also since this is a sync of what is present in the protocol and missing in the code I would remove FragmentData as @ZGako mentioned in #58

**Comment by matteo-dinoia** [comment]
Everything should be fixed, please re-review.

**Comment by DiCesareDaniele** [comment]
> Everything should be fixed, please @DiCesareDaniele (or anyone) re-review.

Yep, everything seems fine

**Pull request merged**
