### PR TITLE
Simulation Controller commands specification 2

### PR DESCRIPTION
**Pull request by DiCesareDaniele**
Duplicate of #72 but Command is split.

```rust
/// From controller to drone
#[derive(Debug, Clone)]
pub enum DroneCommand {
    AddSender(NodeId, Sender<Packet>),
    SetPacketDropRate(f32),
    Crash,
}

/// From drone to controller
#[derive(Debug, Clone)]
pub enum NodeEvent {
    PacketSent(Packet),
    PacketDropped(Packet),
}
```

I have changed the example. It should be better now.
`cargo run --example drone_usage --features="serialize"`
if you want to test it

### CODE REVIEW

**Review by matteo-dinoia — APPROVED** [review]

**Comment by matteo-dinoia** [comment]
Can add server be used to a client server? If so i would change the name to NodeCommand

**Comment by Ro-LiT** [comment]
Example too complete, consider removing it :P

**Comment by DiCesareDaniele** [comment]
> Can add server be used to a client server? If so i would change the name to NodeCommand

No, client/server do not change their topology

DroneCommands can only be sent to drones
NodeEvent can be sent from drones, client, server

**Comment by DiCesareDaniele** [comment]
> Example too complete, consider removing it :P

Nooo R

**Comment by DiCesareDaniele** [comment]
> Example too complete, consider removing it :P

Noooo Rowan ;(

**Comment by RickyBenevelli** [comment]
@matteo-dinoia Can we merge this PR? I think WG approved this yesterday.

**Comment by matteo-dinoia** [comment]
> > Can add server be used to a client server? If so i would change the name to NodeCommand
> 
> No, client/server do not change their topology
> 
> DroneCommands can only be sent to drones NodeEvent can be sent from drones, client, server

But if a drone crash the client should be able to change the topology and maybe connect to new drone.

**Comment by DiCesareDaniele** [comment]
> > > Can add server be used to a client server? If so i would change the name to NodeCommand
> > 
> > 
> > No, client/server do not change their topology
> > DroneCommands can only be sent to drones NodeEvent can be sent from drones, client, server
> 
> But if a drone crash the client should be able to change the topology and maybe connect to new drone.

Right but the client/server and controller are individual so one can handle that case however he likes

**Pull request merged**
