### PR TITLE
Added priority for simulation controller messages

### PR DESCRIPTION
**Pull request by franko-fox**
This change adds mandatory priority for simulation controller messages, so there's no risk that the drones might continuously process messages and never pick up on any important messages (like crashes).
Changes:
- Added a new paragraph in the protocol to enforce this priority
- Used select_biased macro in drone example and swapped the two recv(...) so the simulation controller one is at the top

### CODE REVIEW

**Review by matteo-dinoia — APPROVED** [review]
Fine

**Comment by DiCesareDaniele** [comment]
Deprecated since #79 got merged

**Comment by franko-fox** [comment]
I'm proceeding to close and delete the branch then

**Comment by DiCesareDaniele** [comment]
> I'm proceeding to close and delete the branch then

Can you please reopen this and just change the protocol file? I didn't specify that select biased was forced

**Comment by franko-fox** [comment]
Removed the drone usage edits, and kept only the protocol file change

**Comment by matteo-dinoia** [comment]
> Removed the drone usage edits, and kept only the protocol file change (please ignore cargo fmt not passing)

Is there any problem with cargo fmt?
For the rest, it is ok.

**Comment by franko-fox** [comment]
> > Removed the drone usage edits, and kept only the protocol file change (please ignore cargo fmt not passing)
> 
> Is there any problem with cargo fmt? For the rest, it is ok.

It was complaining about an empty line, I just fixed it.

**Comment by DiCesareDaniele** [comment]
Thank you so much @franko-fox <3. @matteo-dinoia I think now it can be merged

**Comment by matteo-dinoia** [comment]
Did we vote on this? I think not right?

**Comment by Suge42** [comment]
> > Did we vote on this? I think not right?
> > We should probably vote.
> 
> Yes it was in my pr but for some reason it did not got merged. Plus there was an issue about this and everyone who commented said that there was no reason to keep the sim controller trait

If the PR was the one about the Sim commands, in class we voted for the two enums, but not really for the example and the prioritizing of the sim contr commands.
After I've taken a look at all current PR, I'll make a vote for this too on telegram.

**Pull request merged**
