### PR TITLE
Data size in Fragment

### PR DESCRIPTION
**Pull request by RickyBenevelli**
I changed the size of the data array to be a power of 2: from 80 to 128

### CODE REVIEW

**Comment by DiCesareDaniele** [comment]
> I changed the size of the data array to be a power of 2: from 80 to 128

Wholesome. You think we can extract the size into a const?

Like this
```rust
pub const FRAGMENT_DSIZE: usize = 128;

pub struct Fragment {
    pub fragment_index: u64,
    pub total_n_fragments: u64,
    pub length: u8,
    pub data: [u8; FRAGMENT_DSIZE],
}
```

**Comment by franko-fox** [comment]
Why not make the fragment size 1 kilobyte (1024 bytes) or a multiple of that? Since we need to send media through it.

**Comment by Suge42** [comment]
> Why not make the fragment size 1 kilobyte (1024 bytes) or a multiple of that? Since we need to send media through it.

Since also text messages are fragmented, it might be too big, and just send whole messages, which would make the use of fragments useless in that scenario. Sticking to 128 is probably better, but could be discussed.

**Comment by franko-fox** [comment]
> > Why not make the fragment size 1 kilobyte (1024 bytes) or a multiple of that? Since we need to send media through it.
> 
> Since also text messages are fragmented, it might be too big, and just send whole messages, which would make the use of fragments useless in that scenario. Sticking to 128 is probably better, but could be discussed.

Issue with that is that Media will take *forever* to send, since it needs to be split into tiny fragments.

**Comment by matteo-dinoia** [comment]
Please fix merge conflict as i have no write access to your branch since you disabled

**Pull request merged**
