### PR TITLE
Cargo should auto-update wg_repo dependencies

### PR DESCRIPTION
**Pull request by Sm3r**
Added brach param

### CODE REVIEW

**Comment by DiCesareDaniele** [comment]
Cargo already uses main as the default branch

**Comment by matteo-dinoia** [comment]
The problem is about the fact that the dependencies like this don't auto updates. We should add a command to update the `wg_repo` dependency.

**Comment by DiCesareDaniele** [comment]
Yeah but adding main as branch does not auto-update

See
https://github.com/rust-lang/cargo/pull/8561
> Once a `git` dependency has been added, Cargo will lock that dependency to the
latest commit at the time. New commits will not be pulled down automatically
once the lock is in place. However, they can be pulled down manually with
`cargo update`.

And
https://github.com/rust-lang/cargo/blob/master/src/doc/src/reference/specifying-dependencies.md?plain=1#L274C1-L275C65

> Cargo locks the commits of git dependencies in Cargo.lock file at the time of their addition and checks for updates only when you run cargo update command

**Comment by matteo-dinoia** [comment]
Sure yes, just saying we should add this to the README.md (the thing you are saying).

**Comment by DiCesareDaniele** [comment]
> Sure yes, just saying we should add this to the README.md (the thing you are saying).

Sorry my bad

**Pull request closed without merging**
